// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4qNAnVtM0Q6JyeO6MBZzqmj_mXav9jas',
    appId: '1:169445089743:web:3f0a858db9af23e21f32ba',
    messagingSenderId: '169445089743',
    projectId: 'sensor-test-f146b',
    authDomain: 'sensor-test-f146b.firebaseapp.com',
    storageBucket: 'sensor-test-f146b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZGNw5-Qak7RIL6fhte_V5KhYThSyiEQ',
    appId: '1:169445089743:android:2ccad4de5c84e7831f32ba',
    messagingSenderId: '169445089743',
    projectId: 'sensor-test-f146b',
    storageBucket: 'sensor-test-f146b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVkth9hAdOQhlgEyh2tfoeUgqpikm_H7s',
    appId: '1:169445089743:ios:7cdb62ad022a41561f32ba',
    messagingSenderId: '169445089743',
    projectId: 'sensor-test-f146b',
    storageBucket: 'sensor-test-f146b.appspot.com',
    iosClientId: '169445089743-ge1na0uf34v5n8j1cl84rnf0auud2nsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sensorTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVkth9hAdOQhlgEyh2tfoeUgqpikm_H7s',
    appId: '1:169445089743:ios:7cdb62ad022a41561f32ba',
    messagingSenderId: '169445089743',
    projectId: 'sensor-test-f146b',
    storageBucket: 'sensor-test-f146b.appspot.com',
    iosClientId: '169445089743-ge1na0uf34v5n8j1cl84rnf0auud2nsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sensorTest',
  );
}
